spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/blogv2
    username: root
    password: tuanpa28
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        show_sql: true
        format_sql: false
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#      enabled: 'true'
#      file-size-threshold: 2KB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: '587'
    username: hunga1k15tv@gmail.com
    password: gyarrwtufnnnmnaa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  mvc:
#    servlet:
#      path: /api
jwt:
  secret: tuanpa
my:
  secret:
    password: ${random.value}
#file:
#  upload-dir: /opt/wildfly/uploads
#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#  ip: tuanpa
#  artifcate: blog
#
#template:
#  email: classpath:/templates
logging:
  level:
    root : INFO
    dev : INFO
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure: INFO
      hibernate : ERROR
debug: false

